### ISSUE TITLE
Make "Packages" tab default to "Addons"

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-hearth#4]
At the moment, when you click the "Packages" tab for a project, it goes to the "npm" sub-tab.
We would like for it to go to the "Addons" sub-tab instead.

**Comment by ynnoj** [comment]
@locks I'll take this.

**Comment by locks** [comment]
@ynnoj thank you 😄  ping us in #e-hearth (Slack) if you bump into any problems!
