### ISSUE TITLE
Fix "Transform" dropdown for Model maker panel

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-hearth#7]
The "Transform" dropdown in the "Model maker" panel seems to be showing too much information. It needs to be filtered:
![Transform dropdown options - Ember Hearth](https://cloud.githubusercontent.com/assets/32344/17326492/990c77f8-58a9-11e6-8bad-410a5a1849c8.png)

**Comment by locks** [comment]
https://github.com/ember-learn/ember-hearth/pull/9 fixes this, correct?

**Comment by makepanic** [comment]
yes
